"""Capture session facts in an ignored journal without asking an agent to maintain state.

A client end-of-session hook may call this module. It records branch, HEAD, commits since the
last capture, and uncommitted files. It does not invent semantic next steps. Output lives in
an ignored runtime directory, and an unchanged repository produces no new entry.

This neutral implementation is vendored from tool-template and owned by the generated
repository.
"""
from __future__ import annotations

import subprocess
import sys
from datetime import datetime
from pathlib import Path

from .fs import atomic_write, ensure_state_dir


def _git(repo_root: Path, *args: str) -> str:
    proc = subprocess.run(["git", *args], capture_output=True, text=True, cwd=repo_root)
    return proc.stdout.strip() if proc.returncode == 0 else ""


def capture(repo_root: Path) -> Path | None:
    """Append session facts to the ignored journal, or return None when nothing changed."""

    if not (repo_root / ".git").exists():
        return None

    journal_dir = ensure_state_dir(repo_root / ".agent" / "journal")
    marker = journal_dir / ".last-capture"

    branch = _git(repo_root, "rev-parse", "--abbrev-ref", "HEAD") or "-"
    head = _git(repo_root, "rev-parse", "HEAD")
    dirty = _git(repo_root, "status", "--porcelain")
    last_head = marker.read_text().strip() if marker.is_file() else ""

    if head == last_head and not dirty:
        return None

    if last_head:
        commits = _git(repo_root, "log", "--oneline", f"{last_head}..{head}")
    else:
        commits = _git(repo_root, "log", "--oneline", "-5")

    now = datetime.now()
    lines = [f"## {now:%H:%M} - branch {branch} @ {head[:9] or '-'}"]
    if commits:
        lines.append("commits since previous capture:")
        lines += [f"- {commit}" for commit in commits.splitlines()]
    if dirty:
        files = dirty.splitlines()
        lines.append(f"uncommitted: {len(files)} files")
        lines += [f"- {file.strip()}" for file in files[:15]]
        if len(files) > 15:
            lines.append(f"- ... {len(files) - 15} more")
    diffstat = _git(repo_root, "diff", "--shortstat")
    if diffstat:
        lines.append(f"diff: {diffstat}")
    day_file = journal_dir / f"{now:%Y-%m-%d}.md"
    if day_file.exists():
        before = day_file.read_text(encoding="utf-8").rstrip()
    else:
        before = f"# Journal {now:%Y-%m-%d} (generated by session capture; do not edit)"
    # Separate blocks with one blank line and end with exactly one newline so generated
    # journals pass ``git diff --check``.
    atomic_write(day_file, before + "\n\n" + "\n".join(lines) + "\n")
    marker.write_text(head)
    return day_file


def main() -> int:
    """Capture from the project working directory and never break client shutdown."""

    root = _git(Path.cwd(), "rev-parse", "--show-toplevel")
    capture(Path(root) if root else Path.cwd())
    return 0


if __name__ == "__main__":
    sys.exit(main())
